services:
  outlook-email-client:
    build: .
    container_name: outlook-email-api
    ports:
      - "8000:8000"
    volumes:
      # 账户信息持久化
      - outlook-data:/app/data
    environment:
      # 可以通过环境变量覆盖默认配置
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8000
      # 安全配置（生产环境中请修改这些值）
      - ADMIN_PASSWORD=admin123
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - outlook-network

networks:
  outlook-network:
    driver: bridge

volumes:
  outlook-data:
    driver: local 